### ISSUE TITLE
uRNN code

### ISSUE THREAD

**Issue by casperkaae** [amarshah/complex_RNN#1]
Hi Amar and Martin

I've read your uRNN paper and the following reddit discussion with great interest. At reddit you mention that you have a code that is 4x faster than the one on github. 
https://www.reddit.com/r/MachineLearning/comments/3uk2q5/151106464_unitary_evolution_recurrent_neural/cxfwsqw

is the current github version the faster code or is that not released yet? 

BR Casper

**Comment by martinarjovsky** [comment]
It is indeed the current version on github.

Best,
Martin

**Comment by casperkaae** [comment]
Great, thanks

The results seems very impressive! Any chance you have some results from experiments on other datasets that you would like to share ?

**Comment by martinarjovsky** [comment]
Thanks! We do have similar results on other datasets, but they are still a
work in progress as we are trying different new versions of the model. We
will publish them in the future when they are ready.

As a side note to the original comment, we will continue to push
optimization changes as well since there is still room for improvement.

Best!
Martin

**Comment by casperkaae** [comment]
Thats good to hear, sometimes it's struggle when leaving MNIST :)

Thanks for sharing the code

BR
Casper
